function createPolicies() {
  return [
    {
      id: "ai-cost-limit",
      name: "AI Cost Limit",
      description: "Monthly AI inference cost must not exceed threshold",
      version: 1,
      type: "ai",
      severity: "critical",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "cost", "inference", "budget"],
      conditions: [{ field: "ai.cost.monthly", operator: "gt", value: 5000 }],
      actions: [{ type: "deny", message: "Monthly AI cost exceeds $5,000 limit" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-rate-limit",
      name: "AI Rate Limit",
      description: "Max AI requests per minute",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "rate", "limit", "requests"],
      conditions: [{ field: "ai.rate.requests_per_minute", operator: "gt", value: 1000 }],
      actions: [{ type: "deny", message: "AI request rate exceeds 1,000 requests per minute" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-model-restriction",
      name: "AI Model Restriction",
      description: "Only allow approved AI models",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "model", "restriction", "security"],
      conditions: [{ field: "ai.model.name", operator: "not_in", value: ["gpt-4-mini", "claude-3-haiku"] }],
      actions: [{ type: "block", message: "AI model is not in the approved list" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-content-filter",
      name: "AI Content Filter",
      description: "Filter inappropriate AI content",
      version: 1,
      type: "ai",
      severity: "critical",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "content", "filter", "moderation"],
      conditions: [{ field: "ai.output.toxicity_score", operator: "gt", value: 0.7 }],
      actions: [{ type: "block", message: "AI output toxicity score exceeds threshold" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-latency-sla",
      name: "AI Latency SLA",
      description: "AI response must be under threshold",
      version: 1,
      type: "ai",
      severity: "medium",
      enforcement: "soft",
      enabled: true,
      tags: ["ai", "latency", "sla", "performance"],
      conditions: [{ field: "ai.latency.p95", operator: "gt", value: 5000 }],
      actions: [{ type: "warn", message: "AI p95 latency exceeds 5,000ms SLA threshold" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-cost-per-project",
      name: "AI Cost Per Project",
      description: "Per-project AI budget",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "cost", "project", "budget"],
      conditions: [{ field: "ai.cost.project_monthly", operator: "gt", value: 2000 }],
      actions: [{ type: "require_approval", message: "Project monthly AI cost exceeds $2,000" }],
      approval: { required: true, workflow: "budget-approval-flow", approvers: ["finance-manager", "engineering-lead"] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-fallback-enabled",
      name: "AI Fallback Enabled",
      description: "Require fallback model",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "fallback", "reliability"],
      conditions: [{ field: "ai.fallback.enabled", operator: "eq", value: false }],
      actions: [{ type: "deny", message: "AI fallback model must be enabled" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-temperature-limit",
      name: "AI Temperature Limit",
      description: "Max temperature for generations",
      version: 1,
      type: "ai",
      severity: "low",
      enforcement: "soft",
      enabled: true,
      tags: ["ai", "temperature", "generation", "quality"],
      conditions: [{ field: "ai.model.temperature", operator: "gt", value: 1.5 }],
      actions: [{ type: "warn", message: "AI model temperature exceeds 1.5 limit" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-token-limit",
      name: "AI Token Limit",
      description: "Max tokens per request",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "token", "limit", "request"],
      conditions: [{ field: "ai.model.max_tokens", operator: "gt", value: 8192 }],
      actions: [{ type: "deny", message: "AI request exceeds 8,192 token limit" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    },
    {
      id: "ai-batch-size-limit",
      name: "AI Batch Size Limit",
      description: "Max batch size",
      version: 1,
      type: "ai",
      severity: "high",
      enforcement: "hard",
      enabled: true,
      tags: ["ai", "batch", "size", "limit"],
      conditions: [{ field: "ai.batch.size", operator: "gt", value: 50 }],
      actions: [{ type: "deny", message: "AI batch size exceeds 50 limit" }],
      approval: { required: false, workflow: null, approvers: [] },
      metadata: {},
      createdAt: Date.now(),
      updatedAt: Date.now()
    }
  ];
}

function getPolicy(id) {
  return createPolicies().find(p => p.id === id) || null;
}

function getPoliciesByType(type) {
  return createPolicies().filter(p => p.type === type);
}

module.exports = { createPolicies, getPolicy, getPoliciesByType };
