function html(data) {
  const ds = data.designSystem;
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escape(data.project_name)}</title>
<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
<nav class="navbar">
  <div class="nav-brand">${escape(data.project_name)}</div>
  <div class="nav-links">
    <a href="#">Home</a>
    <a href="#">About</a>
    <a href="#">Services</a>
    <a href="#">Contact</a>
  </div>
</nav>
<section class="hero">
  <h1>${escape(data.project_name)}</h1>
  <p class="hero-sub">Built with the Agent Pack — Design System Engine v1</p>
  <a href="#" class="btn">Get Started</a>
</section>
<section class="features">
  <div class="feature-card">
    <h3>Design System</h3>
    <p>CSS variables, design tokens, and theme mapping auto-generated from your brand colors.</p>
  </div>
  <div class="feature-card">
    <h3>Semantic Colors</h3>
    <p>Background, text, surface, border, hover, and active states computed for accessibility.</p>
  </div>
  <div class="feature-card">
    <h3>Theme Aware</h3>
    <p>Light or dark theme detected from your palette luminance automatically.</p>
  </div>
</section>
<footer class="footer">
  <p>&copy; ${new Date().getFullYear()} ${escape(data.project_name)} — Generated by Scaffold Engine v1</p>
</footer>
<script src="assets/js/main.js"></script>
</body>
</html>
`;
}

function readme(data) {
  const ds = data.designSystem;
  let extras = '';
  if (ds) {
    extras = `
## Design System
- Theme: ${ds.tokens.theme}
- Primary: ${ds.tokens.colors.primary || 'none'}
- Secondary: ${ds.tokens.colors.secondary || 'none'}
- Accent: ${ds.tokens.colors.accent || 'none'}
- Palette: ${ds.tokens.palette.length} colors
- See \`assets/design-system.json\` for full tokens
`;
  }
  return `# ${escape(data.project_name)}

## Stack
- HTML / CSS / JavaScript (vanilla)
- Mobile-first responsive design
- Design System Engine v1${extras}

## How to run
Open \`index.html\` in any browser.

## Project type
${data.project_type || 'web'}
`;
}

function agents(data) {
  return `# AGENTS.md — ${escape(data.project_name)}

Generated by Project Scaffold Engine v1.

## Rules
- Do not modify the base structure (index.html, assets/, docs)
- Keep root files intact
- Compatible with Agent Pack v1 workflow
`;
}

function architecture(data) {
  const ds = data.designSystem;
  const dsFiles = ds ? `├── assets/
│   ├── css/
│   │   ├── style.css
│   │   └── theme.css
│   ├── js/
│   │   └── main.js
│   ├── img/
│   └── design-system.json
` : `├── assets/
│   ├── css/
│   │   └── style.css
│   ├── js/
│   │   └── main.js
│   └── img/
`;
  return `# Architecture — ${escape(data.project_name)}

## Project structure
\`\`\`
/
├── index.html
${dsFiles}├── README.md
├── AGENTS.md
├── ARCHITECTURE.md
├── CHANGELOG.md
└── .gitignore
\`\`\`

## Philosophy
- Vanilla-first: no frameworks, no build step
- Assets separated from logic and documentation
- Deterministic scaffold generated from prompt maestro
`;
}

function changelog() {
  return `# Changelog

## 0.1.0
- initial scaffold generated by Project Scaffold Engine v1
`;
}

function gitignore() {
  return `node_modules/
.env
.DS_Store
Thumbs.db
`;
}

function styleCss(data) {
  const ds = data.designSystem;
  if (!ds) return '/* scaffold placeholder */\n';

  const m = ds.mapping;
  return `/* Design System — auto-generated */
@import url('theme.css');

*{margin:0;padding:0;box-sizing:border-box}
html{scroll-behavior:smooth}
body{
  background:var(--color-bg);
  color:var(--color-text);
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
  line-height:1.6;
  min-height:100vh
}
a{color:var(--color-primary);text-decoration:none;transition:color .2s}
a:hover{color:var(--color-hover)}

/* NAV */
.navbar{
  display:flex;align-items:center;justify-content:space-between;
  padding:1rem 2rem;
  background:var(--color-surface);
  border-bottom:1px solid var(--color-border);
  position:sticky;top:0;z-index:100
}
.nav-brand{font-weight:700;font-size:1.1rem;color:var(--color-primary)}
.nav-links{display:flex;gap:1.5rem}
.nav-links a{font-size:.9rem;font-weight:500;color:var(--color-text)}
.nav-links a:hover{color:var(--color-primary)}

/* HERO */
.hero{
  text-align:center;
  padding:6rem 2rem 4rem;
  background:var(--color-surface)
}
.hero h1{font-size:clamp(2rem,5vw,3.5rem);color:var(--color-primary);margin-bottom:1rem;font-weight:800}
.hero-sub{font-size:1.1rem;color:var(--color-text);max-width:560px;margin:0 auto 2rem;opacity:.8}
.btn{
  display:inline-block;padding:.85rem 2rem;
  background:var(--color-primary);color:var(--color-text-on-primary);
  border-radius:6px;font-weight:700;font-size:.9rem;
  transition:all .25s;border:none;cursor:pointer;text-decoration:none
}
.btn:hover{background:var(--color-hover);transform:translateY(-2px)}
.btn:active{background:var(--color-active);transform:translateY(0)}

/* FEATURES */
.features{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));
  gap:1.5rem;padding:4rem 2rem;max-width:1000px;margin:0 auto
}
.feature-card{
  background:var(--color-surface);
  border:1px solid var(--color-border);
  border-radius:8px;padding:1.5rem;transition:border-color .2s
}
.feature-card:hover{border-color:var(--color-primary)}
.feature-card h3{color:var(--color-primary);margin-bottom:.5rem;font-size:1.1rem}
.feature-card p{font-size:.9rem;color:var(--color-text);opacity:.8;line-height:1.6}

/* FOOTER */
.footer{
  text-align:center;padding:2rem;
  border-top:1px solid var(--color-border);
  font-size:.85rem;color:var(--color-text);opacity:.6;
  margin-top:4rem
}

/* UTILITY */
.surface{background:var(--color-surface);color:var(--color-text);border:1px solid var(--color-border)}

@media(max-width:600px){
  .navbar{flex-direction:column;gap:.75rem;padding:.75rem 1rem}
  .nav-links{flex-wrap:wrap;justify-content:center}
  .hero{padding:4rem 1.5rem 3rem}
  .features{padding:2rem 1.5rem}
}
`;
}

function mainJs(data) {
  const ds = data.designSystem;
  if (!ds) return '// scaffold placeholder\n';

  const tokens = JSON.stringify(ds.tokens, null, 2).replace(/`/g, '\\`');
  return `// Design System — auto-generated
const designTokens = ${tokens};

console.log('[Design System] Theme:', designTokens.theme);
console.log('[Design System] Primary:', designTokens.colors.primary);
`;
}

function themeCss(data) {
  const ds = data.designSystem;
  if (!ds) return '';
  return ds.css;
}

function designSystemJson(data) {
  const ds = data.designSystem;
  if (!ds) return '';
  return JSON.stringify(ds.tokens, null, 2) + '\n';
}

function escape(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = {
  templates: {
    html, readme, agents, architecture, changelog, gitignore,
    styleCss, mainJs, themeCss, designSystemJson
  }
};
