function html(data) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escape(data.project_name)}</title>
<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
<h1>${escape(data.project_name)}</h1>
<script src="assets/js/main.js"></script>
</body>
</html>
`;
}

function readme(data) {
  return `# ${escape(data.project_name)}

## Stack
- HTML / CSS / JavaScript (vanilla)
- Mobile-first responsive design

## How to run
Open \`index.html\` in any browser.

## Project type
${data.project_type || 'web'}
`;
}

function agents(data) {
  return `# AGENTS.md — ${escape(data.project_name)}

Generated by Project Scaffold Engine v1.

## Rules
- Do not modify the base structure (index.html, assets/, docs)
- Keep root files intact
- Compatible with Agent Pack v1 workflow
`;
}

function architecture(data) {
  return `# Architecture — ${escape(data.project_name)}

## Project structure
\`\`\`
/
├── index.html
├── assets/
│   ├── css/
│   ├── js/
│   └── img/
├── README.md
├── AGENTS.md
├── ARCHITECTURE.md
├── CHANGELOG.md
└── .gitignore
\`\`\`

## Philosophy
- Vanilla-first: no frameworks, no build step
- Assets separated from logic and documentation
- Deterministic scaffold generated from prompt maestro
`;
}

function changelog() {
  return `# Changelog

## 0.1.0
- initial scaffold generated by Project Scaffold Engine v1
`;
}

function gitignore() {
  return `node_modules/
.env
.DS_Store
Thumbs.db
`;
}

function escape(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = { templates: { html, readme, agents, architecture, changelog, gitignore } };
